### ISSUE TITLE
Initialize step for postgres database in Jupyterhub

### ISSUE THREAD

**Issue by elventear** [radiasoft/ansible-conf#15]
Start the database once during setup, before the service starts. 

Reference:
```yaml
    - init:
        env:
          - [ POSTGRES_PASSWORD, {{ pillar.postgresql_jupyterhub.admin_pass }} ]
          - [ JPY_PSQL_PASSWORD, {{ pillar.jupyterhub.db_pass }} ]
        cmd: bash /radia-init.sh
```
