### ISSUE TITLE
Refactor rs_firewall

### ISSUE THREAD

**Issue by elventear** [radiasoft/ansible-conf#59]
Leverage firewalld zones to define public and trusted areas, with different settings. 

```yaml
rs_firewall:
  public:
    services: []
    ports: []
  trusted:
    services: []
    ports: []
    
```
