### ISSUE TITLE
unable to run sudo to create ssh keys

### ISSUE THREAD

**Issue by robnagler** [radiasoft/ansible-conf#60]
```
TASK [mpi_cluster/coordinator/pre : create jupyter dirs] ***********************
changed: [cdg1.radiasoft.org] => (item=/var/lib/jupyter/conf)
changed: [cdg1.radiasoft.org] => (item=/var/lib/jupyter/mpi_bin)

TASK [mpi_cluster/coordinator/pre : create coordinator user ssh key] ***********
fatal: [cdg1.radiasoft.org]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: sorry, you must have a tty to run sudo\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by elventear** [comment]
I think using [`become_method`](http://docs.ansible.com/ansible/become.html) might fix the issue.

```yaml
- name: create coordinator user ssh key
  [...]
  become: yes
  become_user: vagrant
  become_method: su
```
